import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import AnimatedPortal from "@/components/home/AnimatedPortal";

export const metadata: Metadata = { title: "Focus Labs Media Group", description: "Ideas deserve a place to exist." };
const features = [["▣", "Plan a project", "Turn ideas into clear steps."], ["□", "Shape a message", "Find the right words faster."], ["⌘", "Compare options", "See possibilities more clearly."]] as const;
const memberships = [["♙", "Free entry", "Start exploring.", false], ["ϟ", "Focus One", "More capacity for your work.", false], ["▤", "One + Academy", "Work and learning.", true], ["◇", "Full ecosystem", "Broader access.", true]] as const;

export default function HomePage() {
  return <div className="stitch-home">
    <section className="stitch-hero"><div className="stitch-container stitch-hero-grid"><div className="stitch-hero-copy"><span className="stitch-kicker">Focus Labs Media Group</span><h1>Ideas deserve<br />a place to exist.</h1><p>We turn ideas into stories, useful tools, and experiences — with intention.</p><Link className="stitch-btn stitch-btn-primary" href="/one">Discover Focus One <span>→</span></Link></div><AnimatedPortal /></div></section>
    <section className="stitch-section stitch-section-raised"><div className="stitch-container stitch-one-grid"><div className="stitch-one-intro"><div><span className="stitch-kicker">Make · Learn · Explore</span><h2 className="stitch-display">Focus One</h2><h3>Less scattered thinking. A clearer next move.</h3><p>Bring an idea, a project, or a decision. Shape it into a plan, a draft, or a direction you can use.</p></div><Link className="stitch-btn stitch-btn-primary" href="/one">See what you can do <span>→</span></Link></div><div className="stitch-one-content"><div className="stitch-feature-list">{features.map(([icon,title,copy])=><article className="stitch-feature" key={title}><i>{icon}</i><div><strong>{title}</strong><p>{copy}</p></div></article>)}</div><div className="stitch-initiative-grid"><article className="stitch-initiative"><span className="stitch-kicker">Two</span><h3>The Academy</h3><p>Learn by doing. Build real capability.</p><small>Coming soon</small><Link href="/academy">Discover Academy →</Link></article><article className="stitch-initiative"><span className="stitch-kicker">Three</span><h3>The Labs</h3><p>See how ideas become real.</p><Link href="/the-labs">Explore the process →</Link></article></div></div></div></section>
    <section className="stitch-section stitch-proof"><div className="stitch-container stitch-proof-grid"><div className="stitch-proof-copy"><h2>Built from real work.</h2><p>Focus Labs grew from a way of working: understand first, create with care, improve through practice.</p><small>Professional work by Omar Rincones through Nika Media.</small></div><div className="stitch-work-grid"><figure><Image src="/media/professional-experience/city-kia-production-b01-19.webp" fill sizes="(max-width:700px) 100vw,26vw" alt="City Kia commercial production"/><figcaption><strong>City Kia</strong><span>Commercial production</span></figcaption></figure><figure><Image src="/media/professional-experience/city-kia-production-b01-15.webp" fill sizes="(max-width:700px) 100vw,26vw" alt="Miss City Kia production"/><figcaption><strong>Miss City Kia</strong><span>Production on location</span></figcaption></figure></div></div></section>
    <section className="stitch-section stitch-section-raised"><div className="stitch-container"><span className="stitch-kicker">Memberships</span><h2 className="stitch-section-title">Start with One. Grow with the ecosystem.</h2><div className="stitch-memberships">{memberships.map(([icon,title,copy,planned])=><article key={title}><div className="stitch-card-top"><i>{icon}</i>{planned&&<small>Planned</small>}</div><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div><p className="stitch-note">Membership direction — availability and details to be announced.</p></div></section>
    <section className="stitch-cta"><div className="stitch-cta-image"/><div className="stitch-container stitch-cta-content"><h2>Have an idea worth building?</h2><h3>There’s a place to start.</h3><div><Link className="stitch-btn stitch-btn-primary" href="/one">Open Focus One <span>→</span></Link><a className="stitch-btn stitch-btn-ghost" href="mailto:hello@focuslabsmediagroup.com">Contact Focus Labs</a></div></div></section>
  </div>;
}
